---

    - name: "Configure local git repository"
      listen: git_sync
      shell: "git config {{ item.key | quote }} {{ item.value | quote }}"
      run_once: yes
      changed_when: false
      args:
        chdir: "{{ r_tempfile.path }}"
      loop_control:
        label: "{{ item.key }}: {{ item.value }}"
      loop:
        - { key: user.name, value: "colin-mccarthy" }
        - { key: user.email, value: "cmccarth@redhat.com" }
        - { key: branch.autosetupmerge, value: "always" }
        - { key: push.default, value: "current" }

    - name: "git add --all"
      listen: git_sync
      run_once: true
      shell: "git add --all"
      args:
        chdir: "{{ r_tempfile.path }}"

    - name: "git commit"
      listen: git_sync
      run_once: true
      failed_when: false
      changed_when: git_commit.stdout.find("nothing") == -1
      register: git_commit
      shell: git commit -am "Network Backup"
      args:
        chdir: "{{ r_tempfile.path }}"

    - name: "git push"
      listen: git_sync
      run_once: true
      failed_when: git_push.stderr.find("error:") != -1
      changed_when: git_push.stderr.find("up-to-date") == -1
      register: git_push
      shell: git push
      args:
        chdir: "{{ r_tempfile.path }}"

    - name: "Cleanup generated files/directories"
      listen: git_sync
      run_once: true
      file:
        path: "{{ cleanup }}"
        state: absent
      with_items:
        - "{{ r_ios_config.backup_path | dirname }}"
        - "{{ r_tempfile.path }}"
      loop_control:
        loop_var: cleanup
        label: "cleanup {{ cleanup }}"


